project_id = "bmxcjxtjujhwreduwtvz"

[functions.places-autocomplete]
verify_jwt = false

[functions.places-details]
verify_jwt = false

[functions.xaman-check-payload]
verify_jwt = false

[functions.xrpl-build-payment]
verify_jwt = false

[functions.xrpl-build-token-payment]
verify_jwt = false

[functions.xaman-send-payment]
verify_jwt = false

[functions.xrpl-build-mint]
verify_jwt = false

[functions.xrpl-testnet-faucet]
verify_jwt = false

[functions.xrpl-submit-signed]
verify_jwt = false

[functions.ai-debate]
verify_jwt = false
