// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivyughsvcddtqexwaciy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2eXVnaHN2Y2RkdHFleHdhY2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTM5MDQsImV4cCI6MjA3MzA2OTkwNH0.aAY6-8lgJE_cDPB9Uq46YaQkxcOCcmEmXUiCcrGAiDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});